highlighter: pygments
permalink: /:year/:month/:day/:title.html
name: "Hancel's Blog"

author: "hancel.lin"
atom-baseurl: "http://io.hancel.org"
disqus: "hancel"

excerpt_separator:  '<!--more-->'

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml

