highlighter: rouge
permalink: /:year/:month/:day/:title.html
name: "Hancel's Blog"

author: "hancel.lin"
atom-baseurl: "http://my.hancel.org"
disqus: "hancel"
description: "人生而自由，却无往不在枷锁之中"
keyword: "Hancel, 工程师, C++, Web 前端, Python, imlinhanchao"
excerpt_separator:  '<!--more-->'

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml

