title:            Hancel's Blog
description:      Just Make Fun~
url:              /
signoff:          Hancel.Lin
facebook_appid:   imlinhanchao

links:
  - name:         About
    url:          /about
  - name:         Blog
    url:          /
    external:     true
  - name:         GitHub
    url:          http://github.com/imlinhanchao
    external:     true
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart